// <auto-generated />
using System;
using AuctionWebApplication;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuctionWebApplication.Migrations
{
    [DbContext(typeof(DbauctionContext))]
    partial class DbauctionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuctionWebApplication.Models.Auction", b =>
                {
                    b.Property<int>("AuctionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("auction_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuctionId"));

                    b.Property<string>("AuctionDesription")
                        .HasColumnType("text")
                        .HasColumnName("auction_desription");

                    b.Property<string>("AuctionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("auction_name");

                    b.Property<int?>("BidId")
                        .HasColumnType("int")
                        .HasColumnName("bid_id");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime")
                        .HasColumnName("end_time");

                    b.Property<int>("SellerId")
                        .HasColumnType("int")
                        .HasColumnName("seller_id");

                    b.Property<decimal>("StartPrice")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("start_price");

                    b.HasKey("AuctionId");

                    b.HasIndex("BidId");

                    b.HasIndex("SellerId");

                    b.ToTable("Auction", (string)null);
                });

            modelBuilder.Entity("AuctionWebApplication.Models.Bid", b =>
                {
                    b.Property<int>("BidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("bid_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BidId"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("int")
                        .HasColumnName("auction_id");

                    b.Property<DateTime>("BidTime")
                        .HasColumnType("datetime")
                        .HasColumnName("bid_time");

                    b.Property<int>("BidderId")
                        .HasColumnType("int")
                        .HasColumnName("bidder_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("price");

                    b.HasKey("BidId");

                    b.HasIndex("AuctionId");

                    b.HasIndex("BidderId");

                    b.ToTable("Bid", (string)null);
                });

            modelBuilder.Entity("AuctionWebApplication.Models.SoldItem", b =>
                {
                    b.Property<int>("AuctionId")
                        .HasColumnType("int")
                        .HasColumnName("auction_id");

                    b.Property<int>("BidderId")
                        .HasColumnType("int")
                        .HasColumnName("bidder_id");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("final_price");

                    b.HasIndex("AuctionId");

                    b.HasIndex("BidderId");

                    b.ToTable("SoldItem", (string)null);
                });

            modelBuilder.Entity("AuctionWebApplication.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("password");

                    b.HasKey("UserId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("AuctionWebApplication.Models.Auction", b =>
                {
                    b.HasOne("AuctionWebApplication.Models.Bid", "Bid")
                        .WithMany("Auctions")
                        .HasForeignKey("BidId")
                        .HasConstraintName("FK_Auction_Bid");

                    b.HasOne("AuctionWebApplication.Models.User", "Seller")
                        .WithMany("Auctions")
                        .HasForeignKey("SellerId")
                        .IsRequired()
                        .HasConstraintName("FK_Auction_User");

                    b.Navigation("Bid");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("AuctionWebApplication.Models.Bid", b =>
                {
                    b.HasOne("AuctionWebApplication.Models.Auction", "Auction")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .IsRequired()
                        .HasConstraintName("FK_Bid_Auction");

                    b.HasOne("AuctionWebApplication.Models.User", "Bidder")
                        .WithMany("Bids")
                        .HasForeignKey("BidderId")
                        .IsRequired()
                        .HasConstraintName("FK_Bid_User");

                    b.Navigation("Auction");

                    b.Navigation("Bidder");
                });

            modelBuilder.Entity("AuctionWebApplication.Models.SoldItem", b =>
                {
                    b.HasOne("AuctionWebApplication.Models.Auction", "Auction")
                        .WithMany()
                        .HasForeignKey("AuctionId")
                        .IsRequired()
                        .HasConstraintName("FK_SoldItem_Auction");

                    b.HasOne("AuctionWebApplication.Models.User", "Bidder")
                        .WithMany()
                        .HasForeignKey("BidderId")
                        .IsRequired()
                        .HasConstraintName("FK_SoldItem_User");

                    b.Navigation("Auction");

                    b.Navigation("Bidder");
                });

            modelBuilder.Entity("AuctionWebApplication.Models.Auction", b =>
                {
                    b.Navigation("Bids");
                });

            modelBuilder.Entity("AuctionWebApplication.Models.Bid", b =>
                {
                    b.Navigation("Auctions");
                });

            modelBuilder.Entity("AuctionWebApplication.Models.User", b =>
                {
                    b.Navigation("Auctions");

                    b.Navigation("Bids");
                });
#pragma warning restore 612, 618
        }
    }
}
